version: '3.9'

services:
  backend:
    build:
      context: ./flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/back
    environment:
      FLASK_ENV: development
    command: ["flask", "run", "--host=0.0.0.0"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/front
    command: ["npm", "start"]
